global using Xunit;
global using Moq;
global using FluentAssertions;
global using AutoFixture.Xunit2;
global using Microsoft.Extensions.DependencyInjection;
global using DependencyInjection.Domain;
global using DependencyInjection.Domain.Interfaces;
global using DependencyInjection.Application;
global using DependencyInjection.Infrastructure;